In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.7420,  0.7579,  1.3048],
        [-0.2224,  0.1419,  0.2458]], requires_grad=True)
tensor([-0.2485, -0.8112], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 52.4750,   3.0293],
        [ 82.4365,   7.1674],
        [112.4413,  13.1123],
        [  4.9386,  -8.3026],
        [112.6520,  14.6711]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(4104.1309, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.7420,  0.7579,  1.3048],
        [-0.2224,  0.1419,  0.2458]], requires_grad=True)
tensor([[ -354.2949,  -159.1337,   -79.1337],
        [-7135.4849, -8154.5703, -4963.5474]])


In [13]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [14]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 52.4750,   3.0293],
        [ 82.4365,   7.1674],
        [112.4413,  13.1123],
        [  4.9386,  -8.3026],
        [112.6520,  14.6711]], grad_fn=<AddBackward0>)


In [15]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(4104.1309, grad_fn=<DivBackward0>)


In [16]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -354.2949,  -159.1337,   -79.1337],
        [-7135.4849, -8154.5703, -4963.5474]])
tensor([ -3.2113, -86.0645])


In [17]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [18]:
print(w)
print(b)

tensor([[-0.7384,  0.7595,  1.3056],
        [-0.1511,  0.2235,  0.2954]], requires_grad=True)
tensor([-0.2485, -0.8104], requires_grad=True)


In [19]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2809.2202, grad_fn=<DivBackward0>)


In [20]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [21]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(53.8819, grad_fn=<DivBackward0>)


In [22]:
# Predictions
preds

tensor([[ 55.6048,  72.6743],
        [ 85.5766, 100.0368],
        [113.5369, 130.5939],
        [ 12.7002,  51.3231],
        [112.6246, 109.5272]], grad_fn=<AddBackward0>)

In [23]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [24]:
import torch.nn as nn

In [25]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [26]:
from torch.utils.data import TensorDataset

In [27]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [28]:
from torch.utils.data import DataLoader

In [29]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [30]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.],
        [119., 133.]])


In [31]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2017, -0.2537, -0.5108],
        [-0.4448, -0.0933, -0.1757]], requires_grad=True)
Parameter containing:
tensor([0.1944, 0.1691], requires_grad=True)


In [32]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2017, -0.2537, -0.5108],
         [-0.4448, -0.0933, -0.1757]], requires_grad=True),
 Parameter containing:
 tensor([0.1944, 0.1691], requires_grad=True)]

In [33]:
# Generate predictions
preds = model(inputs)
preds


tensor([[-53.4939, -46.1147],
        [-73.1796, -59.7723],
        [-80.9757, -61.2325],
        [-50.1917, -55.7206],
        [-73.8355, -51.7869],
        [-53.4939, -46.1147],
        [-73.1796, -59.7723],
        [-80.9757, -61.2325],
        [-50.1917, -55.7206],
        [-73.8355, -51.7869],
        [-53.4939, -46.1147],
        [-73.1796, -59.7723],
        [-80.9757, -61.2325],
        [-50.1917, -55.7206],
        [-73.8355, -51.7869]], grad_fn=<AddmmBackward>)

In [34]:
# Import nn.functional
import torch.nn.functional as F

In [35]:
# Define loss function
loss_fn = F.mse_loss

In [36]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(22705.4883, grad_fn=<MseLossBackward>)


In [37]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [38]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [39]:
fit(100, model, loss_fn, opt)

Epoch [10/100], Loss: 263.6856
Epoch [20/100], Loss: 297.9986
Epoch [30/100], Loss: 316.9756
Epoch [40/100], Loss: 111.4712
Epoch [50/100], Loss: 45.6920
Epoch [60/100], Loss: 38.9662
Epoch [70/100], Loss: 140.1979
Epoch [80/100], Loss: 47.3144
Epoch [90/100], Loss: 39.7859
Epoch [100/100], Loss: 18.0513


In [40]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.6864,  71.2989],
        [ 79.1562,  97.7736],
        [122.7010, 137.4641],
        [ 29.7048,  42.6289],
        [ 91.6553, 110.8930],
        [ 58.6864,  71.2989],
        [ 79.1562,  97.7736],
        [122.7010, 137.4641],
        [ 29.7048,  42.6289],
        [ 91.6553, 110.8930],
        [ 58.6864,  71.2989],
        [ 79.1562,  97.7736],
        [122.7010, 137.4641],
        [ 29.7048,  42.6289],
        [ 91.6553, 110.8930]], grad_fn=<AddmmBackward>)