In [2]:
#General Integration
import scipy.integrate as integrate
import scipy.special as special

In [3]:
#bessel function(2.5,x)

In [4]:
result = integrate.quad(lambda x: special.jv(2.5,x), 0, 4.5)

In [5]:
result

(1.1178179380783244, 7.866317216380707e-09)

In [6]:
#another bessel function
result = integrate.quad(lambda x: special.jv(10,x), 0, 4.5)
result

(0.00025275139999817467, 2.8061042378421627e-18)

In [7]:
from numpy import sqrt, sin, cos, pi
#fresnel
I = sqrt(2/pi)*(18.0/27*sqrt(2)*cos(4.5) - 4.0/27*sqrt(2)*sin(4.5) +
                sqrt(2*pi) * special.fresnel(3/sqrt(pi))[0])
I

1.117817938088701

In [8]:
print(abs(result[0]-I))

1.1175651866887029


In [9]:
#ADDITIONAL PARAMETERS
from scipy.integrate import quad
def integrand(x, a, b):
    return a*x**2 + b
a = 2
b = 1
I = quad(integrand, 0, 1, args=(a,b))
I


(1.6666666666666667, 1.8503717077085944e-14)

In [14]:
#Special exponential
import numpy as np
from numpy import array
def integrand(t, n, x):
    return np.exp(-x*t) / t**n

In [15]:
def expint(n, x):
    return quad(integrand, 1, np.inf, args=(n, x))[0]
vec_expint = np.vectorize(expint)
vec_expint(3, np.arange(1.0, 4.0, 0.5))
array([ 0.1097,  0.0567,  0.0301,  0.0163,  0.0089,  0.0049])
import scipy.special as special
special.expn(3, np.arange(1.0,4.0,0.5))


array([0.10969197, 0.05673949, 0.03013338, 0.01629537, 0.00893065,
       0.00494538])

In [16]:
#Multiple Integration
#need dblquad and tplquad
from scipy.integrate import quad, dblquad
def I(n):
    return dblquad(lambda t, x: np.exp(-x*t)/t**n, 0, np.inf, lambda x: 1, lambda x: np.inf)

In [17]:
print(I(1))

(0.9999999983857643, 1.1492024121278991e-07)


In [18]:
print(I(20))

(0.049999999999984876, 2.7143743394995246e-09)


In [19]:
print(I(100))

(0.010000000000118046, 1.4085861224338622e-08)


In [20]:
#For n-fold integration need nquad
from scipy import integrate
N = 5
def f(t, x):
   return np.exp(-x*t) / t**N
integrate.nquad(f, [[1, np.inf],[0, np.inf]])

(0.2000000000189363, 1.3682975855986121e-08)

In [21]:
#Can use for non-constant limits
def f(x, y):
    return x*y

def bounds_y():
    return [0, 0.5]

def bounds_x(y):
    return [0, 1-2*y]
integrate.nquad(f, [bounds_x, bounds_y])

(0.010416666666666668, 4.101620128472366e-16)

In [28]:
#Gaussian quadrature
I = lambda x: x**8 + x**4
J = integrate.quadrature(I, 0.0, 1.8)
print(J)

(25.81905715199999, 0.0)


In [39]:
#Romberg Integration
import sys
def integrate(fn, a, b, steps=5, debug=False, exact=None):
    table = np.zeros((steps, steps), dtype=np.float64)
    pow_4 = 4 ** np.arange(steps, dtype=np.float64) - 1
    # trapezoidal rule
    h = (b - a)
    table[0, 0] = h * (fn(a) + fn(b)) / 2
    for j in range(1, steps):
        h /= 2
        # extended trapezoidal rule
        table[j, 0] = table[j - 1, 0] / 2
        table[j, 0] += h * np.sum(
            fn(a + i * h) for i in range(1, 2 ** j + 1, 2)
        )
        # richardson extrapolation
        for k in range(1, j + 1):
            table[j, k] = table[j, k - 1] + \
                (table[j, k - 1] - table[j - 1, k - 1]) / pow_4[k]
# debug
    if debug:
        print(table, file=sys.stderr)
        if exact is not None:
            errors = [
                '%.2e' % i 
                for i in np.abs(table.diagonal() - exact)
             ]
            print('abs. error:', errors, file=sys.stderr)
    return table[-1, -1]

In [40]:
integrate(lambda x: np.exp(-x * x), 0, 1, 
          debug=True, exact=0.746824132812427)

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  
[[0.68393972 0.         0.         0.         0.        ]
 [0.73137025 0.74718043 0.         0.         0.        ]
 [0.7429841  0.74685538 0.74683371 0.         0.        ]
 [0.74586561 0.74682612 0.74682417 0.74682402 0.        ]
 [0.7465846  0.74682426 0.74682413 0.74682413 0.74682413]]
abs. error: ['6.29e-02', '3.56e-04', '9.58e-06', '1.14e-07', '2.83e-10']


0.7468241330950943

In [43]:
#Using samples
def f1(x):
   return x**2
x = np.array([1,3,4])
y1 = f1(x)
from scipy.integrate import simps
I1 = simps(y1, x)
print(I1)

21.0
